# Main menu navigation (導航目錄)
menu:
  Home: / || fas fa-home
  Categories: /categories/ || fas fa-folder-open
  Tags: /tags/ || fas fa-tags
  Archives: /archives/ || fas fa-archive
  About: /about/ || fas fa-user

# Code Blocks (代碼相關)
highlight_theme: mac # default / darker / pale night / light / ocean / mac / mac light / false
highlight_copy: true # copy button
highlight_lang: true # show the code language
highlight_shrink: false # true: shrink the code blocks / false: expand the code blocks | none: expand code blocks and hide the button
highlight_height_limit: false # unit: px
code_word_wrap: true

# Social Settings (社交圖標設置)
# formal:
#   icon: link || the description
social:
  fab fa-github: https://github.com/JoneyXiao || Github
  fas fa-envelope: mailto:joneyhsiao@outlook.com || Email

# Website Background (設置網站背景)
# can set it to color or image (可設置圖片 或者 顔色)
background: "linear-gradient(to right, rgb(134, 239, 172), rgb(59, 130, 246), rgb(147, 51, 234))"

# Aside Settings (側邊欄設置)
aside:
  enable: true
  hide: false
  button: true
  mobile: true
  position: right
  display:
    archive: true
    tag: true
    category: true
  card_author:
    enable: true
    description: DevOps Interview Questions
    button:
      enable: true
      icon: fab fa-github
      text: Follow Me
      link: https://github.com/JoneyXiao
  card_announcement:
    enable: true
    content: This is a comprehensive collection of DevOps interview questions and answers. Feel free to contribute!
  card_recent_post:
    enable: true
    limit: 5
    sort: date
  card_categories:
    enable: true
    limit: 8
    expand: none
  card_tags:
    enable: true
    limit: 40
    color: false
    orderby: random
  card_archives:
    enable: true
    type: monthly
    format: MMMM YYYY
    order: -1
    limit: 8
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true
    sort_order:

# Main theme color (主題顏色)
theme_color:
  enable: true
  main: "#3498db"
  paginator: "#3498db"
  button_hover: "#2980b9"
  text_selection: "#d6eafb"
  link_color: "#3498db"
  meta_color: "#858585"
  hr_color: "#A4D8FA"
  code_foreground: "#F47466"
  code_background: "rgba(27, 31, 35, .05)"
  toc_color: "#3498db"
  blockquote_padding_color: "#3498db"
  blockquote_background_color: "#f8f9fa"
  scrollbar_color: "#3498db"

# The top_img settings of home page
# default: top img - full screen, site info - middle (默認top_img全屏，site_info在中間)
# The position of site info, eg: 300px/300em/300rem/10% (主頁標題距離頂部距離)
index_site_info_top: 50%
# index_top_img_height: 600px # Commented out to enable full screen
# If the banner of your homepage has background image (主頁banner是否有背景圖)
index_img: https://images.unsplash.com/photo-1742282640962-e8b3fc672c8d?q=80&w=2030&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
full_page_background: true

# If you are using a local image, you can use the relative path: /img/your-image.jpg
# Application to every page (applies to all pages)
top_img: https://images.unsplash.com/photo-1742282640962-e8b3fc672c8d?q=80&w=2030&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D

# The user interface setting of category and tag page (category和tag頁的UI設置)
# index - same as homepage UI (index 值代表 UI將與首頁的UI一樣)
# default - same as archives UI 默認跟archives頁面UI一樣
category_ui: index
tag_ui: index

# Website favicon
favicon: /img/devops-colorful.svg

# Avatar (頭像)
avatar:
  img: /img/devops-colorful.svg
  effect: false

# Font settings
# 字體設置
font:
  global-font-size: 16px
  code-font-size: 14px
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", Lato, Roboto, "PingFang SC", "Microsoft JhengHei", "Microsoft YaHei", sans-serif
  code-font-family: consolas, Menlo, "PingFang SC", "Microsoft JhengHei", "Microsoft YaHei", sans-serif

# Article meta
post_meta:
  page:
    date_type: created # created or updated or both 主頁文章日期是創建日或者更新日或都顯示
    date_format: date # date/relative 顯示日期還是相對日期
    categories: true # true or false 主頁是否顯示分類
    tags: true # true or false 主頁是否顯示標籤
    label: true # true or false 顯示描述性文字
  post:
    date_type: both # created or updated or both 文章頁日期是創建日或者更新日或都顯示
    date_format: date # date/relative 顯示日期還是相對日期
    categories: true # true or false 文章頁是否顯示分類
    tags: true # true or false 文章頁是否顯示標籤
    label: true # true or false 顯示描述性文字

# Display the article introduction on homepage
# 1: description
# 2: both (if the description exists, it will show description, or show the auto_excerpt)
# 3: auto_excerpt (default)
index_post_content:
  method: 3
  length: 250 # if you set method to 2 or 3, the length need to config

# Footer Settings
# ------------------------------------
footer:
  owner:
    enable: true
    since: 2025
  custom_text: <a href="https://github.com/JoneyXiao">Follow me on GitHub</a>
  copyright: true # Copyright of theme and framework

# Lightbox (圖片大圖查看模式)
# --------------------------------------
# You can only choose one, or neither
lightbox: mediumZoom

# Pjax
# ------------------------------------
pjax:
  enable: true
  exclude:
    # - xxxx
    # - xxxx

# Inject
# ------------------------------------
inject:
  head:
    - <link rel="stylesheet" href="/css/custom.css">

# CDN
# Don't modify the following settings unless you know how they work
# 非必要請不要修改
CDN:
  # main
  main_css: /css/index.css
  jquery: https://cdn.jsdelivr.net/npm/jquery@latest/dist/jquery.min.js
  main: /js/main.js
  utils: /js/utils.js 
