# ===============================================================
# NexT Theme configuration
# See: https://theme-next.js.org/docs/
# ===============================================================

# ---------------------------------------------------------------
# Scheme Settings
# ---------------------------------------------------------------
# Schemes
#scheme: Muse
scheme: Gemini
#scheme: Pisces
#scheme: Mist

# Dark Mode
darkmode: false

# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------
menu:
  home: / || fa fa-home
  categories: /categories/ || fa fa-th
  tags: /tags/ || fa fa-tags
  archives: /archives/ || fa fa-archive
  about: /about/ || fa fa-user

# ---------------------------------------------------------------
# Sidebar Settings
# ---------------------------------------------------------------
# Use icon instead of the symbol # to indicate the tag count
tagicon: true

# Post wordcount display settings
# Dependencies: https://github.com/next-theme/hexo-word-count
symbols_count_time:
  separated_meta: true
  item_text_post: true
  item_text_total: false

# ---------------------------------------------------------------
# Font Settings
# ---------------------------------------------------------------
# Font families for Gemini scheme
font:
  enable: true
  global:
    external: true
    family: Source Sans Pro
    size: 16

# ---------------------------------------------------------------
# Custom Logo
# ---------------------------------------------------------------
custom_logo:
  enable: false
  image: 

# ---------------------------------------------------------------
# Theme Color
# ---------------------------------------------------------------
theme_color:
  enable: true
  main: "#3498db"
  paginator: "#3498db"
  button_hover: "#3498db"
  code_foreground: "#c7254e"
  code_background: "#f9f2f4"
  text_selection: "#d6eafb"

# ---------------------------------------------------------------
# Back to top and Reading progress
# ---------------------------------------------------------------
back2top:
  enable: true
  sidebar: false
  scrollpercent: true

reading_progress:
  enable: true
  color: "#37c0fb"
  height: 2px

# ---------------------------------------------------------------
# Tag Plugins
# ---------------------------------------------------------------
# Note tag (bs-callout)
note:
  style: modern
  icons: true
  light_bg_offset: 0

# ---------------------------------------------------------------
# Comments Settings
# ---------------------------------------------------------------
comments:
  active: false

# ---------------------------------------------------------------
# Footer Settings
# ---------------------------------------------------------------
footer:
  since: 2024
  icon:
    name: fa fa-code
    animated: true
    color: "#808080"
  copyright: DevOpsMe

# ---------------------------------------------------------------
# Post Settings
# ---------------------------------------------------------------
post_meta:
  updated_at:
    enable: false

# Use icon instead of the symbol # to indicate the tag count
tag_icon: true

# ---------------------------------------------------------------
# Custom Pages
# ---------------------------------------------------------------
# About page
about:
  enable: true

# ---------------------------------------------------------------
# SEO Settings
# ---------------------------------------------------------------
seo: true

# ---------------------------------------------------------------
# Animation Effects
# ---------------------------------------------------------------
motion:
  enable: true
  async: true

# ---------------------------------------------------------------
# Local Search
# ---------------------------------------------------------------
local_search:
  enable: true
  trigger: auto
  top_n_per_article: 1
  unescape: false
  preload: false

# ---------------------------------------------------------------
# Custom CSS/JS Settings
# ---------------------------------------------------------------
custom_file_path:
  style: source/css/custom.styl 